### ISSUE TITLE
Android Studio 0.6.0 upgrade causing "No signature of method" error.

### ISSUE THREAD

**Issue by levibostian** [novoda/robolectric-plugin#15]
Error: ```Error:No signature of method: com.android.build.gradle.LibraryPlugin.getRuntimeJarList() is applicable for argument types: () values: []```

Upgraded to Android Studio 0.6.0 which only edited my build.gradle file to upgrade my android-gradle plugin to version: ```com.android.tools.build:gradle:0.11.+``` After the gradle plugin upgrade and trying a sync, error comes up. Remove this plugin from project, do a sync and error goes away.

**Comment by johnjohndoe** [comment]
@levibostian Any comment or reference on the solution?
